language: python

python:
  - "2.7"
  - "3.3"

branches:
  only:
    - master

env:
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=pypy
    - TOX_ENV=py27 CC=clang
    - TOX_ENV=py32 CC=clang
    - TOX_ENV=py33 CC=clang
    - TOX_ENV=pypy CC=clang
    - TOX_ENV=docs
    - TOX_ENV=pep8
    - TOX_ENV=py3pep8

install:
#    - "[[ ${TOX_ENV} == pypy ]] && sudo add-apt-repository -y ppa:pypy/ppa || true"
#    - "[[ ${TOX_ENV} == pypy ]] && sudo apt-get -y update && sudo apt-get -y install pypy || true"
    # This is required because we need to get rid of the Travis installed PyPy
    # or it'll take precedence over the PPA installed one.
#    - "[[ ${TOX_ENV} == pypy ]] && sudo rm -rf /usr/local/pypy/bin || true"
    - pip install tox

script:
    - tox -e $TOX_ENV

notifications:
#    irc:
#        channels: false
#            - "irc.freenode.org#none"
#        use_notice: true
#        skip_join: true
    email: svaksha@gmail.com
    flowdock: false
    on_success: "change"
    on_failure: "always" 
