language: python

python:
  - "2.7"
  - "3.3"

branches:
  only:
    - master

env:
    - COVERAGE=--with-coverage

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python-pip
    - sudo apt-get install -qq numpy python-scipy python-nose 
    
install:
    - python setup.py build_ext --inplace
    - if [ "${COVERAGE}" == "--with-coverage" ]; then sudo pip install coverage; fi
    - if [ "${COVERAGE}" == "--with-coverage" ]; then sudo pip install coveralls; fi
script:
    - if [ "${COVERAGE}" == "--with-coverage" ]; then
    -   make test-coverage;
    - else
    -   make test;
    - fi
after_success:
    - if [ "${COVERAGE}" == "--with-coverage" ]; then coveralls; fi

notifications:
#    irc:
#        channels: false
#            - "irc.freenode.org#none"
#        use_notice: true
#        skip_join: true
    email: svaksha@gmail.com
    on_success: "change"
    on_failure: "always" 

